--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
-- Dumped by pg_dump version 16.2

-- Started on 2024-05-17 10:25:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 304 (class 1259 OID 30636)
-- Name: jobs; Type: TABLE; Schema: jobscraper; Owner: postgres
--

CREATE TABLE jobscraper.jobs (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    company text,
    short_summary text,
    hard_requirements text,
    score text,
    job_site text,
    url text,
    location text,
    date_posted date,
    comp_interval text,
    comp_min integer,
    comp_max integer,
    comp_currency text,
    emails text,
    description text,
    searched_title text,
    id uuid DEFAULT gen_random_uuid()
);


ALTER TABLE jobscraper.jobs OWNER TO postgres;

--
-- TOC entry 307 (class 1259 OID 30809)
-- Name: role_configs; Type: TABLE; Schema: jobscraper; Owner: postgres
--

CREATE TABLE jobscraper.role_configs (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    role_id integer,
    key text,
    string_value text,
    int_value integer,
    bool_value boolean
);


ALTER TABLE jobscraper.role_configs OWNER TO postgres;

--
-- TOC entry 308 (class 1259 OID 30812)
-- Name: role_config_id_seq; Type: SEQUENCE; Schema: jobscraper; Owner: postgres
--

ALTER TABLE jobscraper.role_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME jobscraper.role_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 305 (class 1259 OID 30797)
-- Name: roles; Type: TABLE; Schema: jobscraper; Owner: postgres
--

CREATE TABLE jobscraper.roles (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text
);


ALTER TABLE jobscraper.roles OWNER TO postgres;

--
-- TOC entry 306 (class 1259 OID 30800)
-- Name: role_id_seq; Type: SEQUENCE; Schema: jobscraper; Owner: postgres
--

ALTER TABLE jobscraper.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME jobscraper.role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3796 (class 0 OID 30809)
-- Dependencies: 307
-- Data for Name: role_configs; Type: TABLE DATA; Schema: jobscraper; Owner: postgres
--

COPY jobscraper.role_configs (id, created_at, role_id, key, string_value, int_value, bool_value) FROM stdin;
1	2024-05-17 13:59:25.245349+00	1	job_titles	Senior UX Designer	\N	\N
2	2024-05-17 13:59:38.266069+00	1	job_titles	Senior Product Designer	\N	\N
3	2024-05-17 13:59:51.248453+00	1	job_titles	UX Lead	\N	\N
4	2024-05-17 14:00:05.031174+00	1	job_titles	UX/UI Designer	\N	\N
5	2024-05-17 14:00:22.240011+00	1	job_titles	User Experience Designer	\N	\N
6	2024-05-17 14:00:38.432313+00	1	is_remote	\N	\N	t
7	2024-05-17 14:00:56.816952+00	1	location	Chapel Hill, NC	\N	\N
8	2024-05-17 14:01:17.616212+00	1	distance	\N	10	\N
9	2024-05-17 14:01:34.915059+00	1	stop_words	Associate	\N	\N
10	2024-05-17 14:01:47.11162+00	1	stop_words	Junior	\N	\N
11	2024-05-17 14:05:19.717127+00	1	stop_words	Manager	\N	\N
12	2024-05-17 14:05:19.717127+00	1	stop_words	Director	\N	\N
13	2024-05-17 14:05:19.717127+00	1	stop_words	Staff	\N	\N
14	2024-05-17 14:05:19.717127+00	1	stop_words	Principal	\N	\N
15	2024-05-17 14:05:19.717127+00	1	stop_words	Developer	\N	\N
16	2024-05-17 14:05:19.717127+00	1	stop_words	Architect	\N	\N
17	2024-05-17 14:05:19.717127+00	1	stop_words	Content	\N	\N
18	2024-05-17 14:05:19.717127+00	1	stop_words	VP	\N	\N
19	2024-05-17 14:06:49.199109+00	1	skill_words	user research	\N	\N
20	2024-05-17 14:06:49.199109+00	1	skill_words	usability testing	\N	\N
21	2024-05-17 14:06:49.199109+00	1	skill_words	strategy	\N	\N
22	2024-05-17 14:06:49.199109+00	1	skill_words	prototyping	\N	\N
23	2024-05-17 14:07:23.850764+00	1	candidate_requirements	401k	\N	\N
24	2024-05-17 14:07:37.653357+00	1	candidate_min_salary	\N	100000	\N
26	2024-05-17 14:18:18.944808+00	3	job_titles	Software Engineer	\N	\N
27	2024-05-17 14:18:18.944808+00	3	job_titles	Software Developer	\N	\N
28	2024-05-17 14:18:18.944808+00	3	job_titles	Web Developer	\N	\N
29	2024-05-17 14:18:18.944808+00	3	job_titles	Full Stack Developer	\N	\N
30	2024-05-17 14:18:18.944808+00	3	is_remote	\N	\N	t
31	2024-05-17 14:18:18.944808+00	3	location	Columbus, OH	\N	\N
32	2024-05-17 14:18:18.944808+00	3	distance	\N	20	\N
33	2024-05-17 14:18:18.944808+00	3	stop_words	Senior	\N	\N
34	2024-05-17 14:18:18.944808+00	3	stop_words	Sr.	\N	\N
35	2024-05-17 14:18:18.944808+00	3	stop_words	III	\N	\N
36	2024-05-17 14:18:18.944808+00	3	stop_words	II	\N	\N
37	2024-05-17 14:18:18.944808+00	3	stop_words	Lead	\N	\N
38	2024-05-17 14:18:18.944808+00	3	stop_words	Internship	\N	\N
39	2024-05-17 14:18:18.944808+00	3	stop_words	Manager	\N	\N
40	2024-05-17 14:18:18.944808+00	3	stop_words	Director	\N	\N
41	2024-05-17 14:18:18.944808+00	3	stop_words	Architect	\N	\N
42	2024-05-17 14:18:18.944808+00	3	skill_words	Python	\N	\N
43	2024-05-17 14:18:18.944808+00	3	skill_words	C#	\N	\N
44	2024-05-17 14:18:18.944808+00	3	skill_words	Java	\N	\N
45	2024-05-17 14:18:18.944808+00	3	skill_words	agile	\N	\N
46	2024-05-17 14:18:18.944808+00	3	candidate_requirements	healthcare coverage	\N	\N
47	2024-05-17 14:18:41.365633+00	2	job_titles	Software Engineering Manager	\N	\N
48	2024-05-17 14:18:41.365633+00	2	job_titles	Director of Software Engineering	\N	\N
49	2024-05-17 14:18:41.365633+00	2	is_remote	\N	\N	t
50	2024-05-17 14:18:41.365633+00	2	location	Cleveland, OH	\N	\N
51	2024-05-17 14:18:41.365633+00	2	distance	\N	20	\N
52	2024-05-17 14:18:41.365633+00	2	skill_words	Agile	\N	\N
53	2024-05-17 14:18:41.365633+00	2	skill_words	Software Development Lifecycle	\N	\N
54	2024-05-17 14:18:41.365633+00	2	skill_words	development team	\N	\N
55	2024-05-17 14:18:41.365633+00	2	resume	AboutAbout\\nDynamic technology leader with a proven track record in assembling and mentoring elite delivery teams, spearheading expansive technology projects, and enhancing team cohesion to achieve measurable outcomes. Recognized for a holistic expertise that encompasses project management, fostering software delivery excellence, driving sales growth, strategic planning, and organizational restructuring. Committed to innovation and results, excels in transforming challenges into opportunities.\\n\\nExperience\\nLeadership Consultant / CTO, VP, DirectorLeadership Consultant / CTO, VP, Director\\nJan 2019 - Present · 5 yrs 4 mos\\nOVERVIEW:\\nHold multiple roles and responsibilities as a Leadership Consultant. Coach, mentor, and transform technical leads into Engineering Managers and Directors, equipping them with the skills and mindset to lead and inspire their teams effectively. Guide and motivate engineering leaders in creating alignment with business partners and leveraging the OKR framework to establish shared goals and strategic buy-in organization-wide.\\n\\nDirector, Product Engineering (2022) – Established Shared Delivery principles and processes across the organization. Create and execute strategies to achieve value stream efficiency and alignment objectives. Foster and execute product concepts from ideation to delivery. Coach and influence teams towards strong adherence to psychological safety and modern delivery practices.\\n\\nConsultant/Leadership Coach (2022) – Mentor engineers transitioning into leadership roles, with a focus on balancing a big-picture/business perspective with an engineering mindset. Coach leaders on strategy development/deployment and engineers on Agile technical practices. Evaluate software delivery capabilities and time-to-market.\\n\\nVice President of Digital (interim), (2020-2021) – Directed all IT functions, including recruitment, hiring, and performance management for all North America. Led a team of 4 Regional Directors. Created the IT strategy, including all performance metrics. Worked with HR and Finance to design and institute a new IT as a Shared Services organizational structure. Led the Dynamics 365 implementation.\\n\\nChief Technology Officer, (2019-2020) – Led a Digital Transformation that paved the way for a significant improvement in product delivery, including planning and delivery of a Digital Signing platform. Recruited, hired, and managed software developers. Ensured 100% compliance with HIPAA and CIS20. Reduced cycle times from 2 months to less than 1 week.	\N	\N
56	2024-05-17 14:20:24.492011+00	4	job_titles	Software Quality Assurance	\N	\N
57	2024-05-17 14:20:24.492011+00	4	job_titles	Software QA	\N	\N
58	2024-05-17 14:20:24.492011+00	4	job_titles	Software QA Manager	\N	\N
59	2024-05-17 14:20:24.492011+00	4	job_titles	Software QA Lead	\N	\N
60	2024-05-17 14:20:24.492011+00	4	job_titles	Software Tester	\N	\N
61	2024-05-17 14:20:24.492011+00	4	is_remote	\N	\N	t
62	2024-05-17 14:20:24.492011+00	4	location	Saint Louis, MO	\N	\N
63	2024-05-17 14:20:24.492011+00	4	distance	\N	20	\N
64	2024-05-17 14:20:24.492011+00	4	stop_words	Pharmacy	\N	\N
65	2024-05-17 14:20:24.492011+00	4	stop_words	Lab	\N	\N
66	2024-05-17 14:20:24.492011+00	4	stop_words	Technician	\N	\N
67	2024-05-17 14:20:24.492011+00	4	stop_words	Tech	\N	\N
68	2024-05-17 14:20:24.492011+00	4	stop_words	Sales	\N	\N
69	2024-05-17 14:20:24.492011+00	4	stop_words	Plant	\N	\N
70	2024-05-17 14:20:24.492011+00	4	stop_words	Maintenance	\N	\N
71	2024-05-17 14:20:24.492011+00	4	stop_words	Manufacturing	\N	\N
72	2024-05-17 14:20:24.492011+00	4	stop_words	Food	\N	\N
73	2024-05-17 14:20:24.492011+00	4	stop_words	Teacher	\N	\N
74	2024-05-17 14:20:24.492011+00	4	stop_words	Scientist	\N	\N
75	2024-05-17 14:20:24.492011+00	4	skill_words	Test cases	\N	\N
76	2024-05-17 14:20:24.492011+00	4	skill_words	quality assurance	\N	\N
77	2024-05-17 14:20:24.492011+00	4	skill_words	test plans	\N	\N
78	2024-05-17 14:20:24.492011+00	4	skill_words	SDLC	\N	\N
79	2024-05-17 14:20:24.492011+00	4	skill_words	Software Development Life Cycle	\N	\N
80	2024-05-17 14:20:24.492011+00	4	skill_words	test automation	\N	\N
81	2024-05-17 14:20:24.492011+00	4	candidate_requirements	Health insurance	\N	\N
\.


--
-- TOC entry 3794 (class 0 OID 30797)
-- Dependencies: 305
-- Data for Name: roles; Type: TABLE DATA; Schema: jobscraper; Owner: postgres
--

COPY jobscraper.roles (id, created_at, name) FROM stdin;
1	2024-05-17 13:48:14.371696+00	Senior UX Researcher
2	2024-05-17 13:48:27.902301+00	Engineering Manager
3	2024-05-17 13:48:45.525022+00	Junior Software Developer
4	2024-05-17 13:48:52.190315+00	Software QA
\.


--
-- TOC entry 3808 (class 0 OID 0)
-- Dependencies: 308
-- Name: role_config_id_seq; Type: SEQUENCE SET; Schema: jobscraper; Owner: postgres
--

SELECT pg_catalog.setval('jobscraper.role_config_id_seq', 81, true);


--
-- TOC entry 3809 (class 0 OID 0)
-- Dependencies: 306
-- Name: role_id_seq; Type: SEQUENCE SET; Schema: jobscraper; Owner: postgres
--

SELECT pg_catalog.setval('jobscraper.role_id_seq', 4, true);


--
-- TOC entry 3641 (class 2606 OID 30820)
-- Name: role_configs role_config_pkey; Type: CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.role_configs
    ADD CONSTRAINT role_config_pkey PRIMARY KEY (id);


--
-- TOC entry 3639 (class 2606 OID 30808)
-- Name: roles role_pkey; Type: CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.roles
    ADD CONSTRAINT role_pkey PRIMARY KEY (id);


--
-- TOC entry 3642 (class 2606 OID 30821)
-- Name: role_configs role_config_role_id_fkey; Type: FK CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.role_configs
    ADD CONSTRAINT role_config_role_id_fkey FOREIGN KEY (role_id) REFERENCES jobscraper.roles(id);


--
-- TOC entry 3803 (class 0 OID 0)
-- Dependencies: 304
-- Name: TABLE jobs; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON TABLE jobscraper.jobs TO anon;
GRANT ALL ON TABLE jobscraper.jobs TO authenticated;
GRANT ALL ON TABLE jobscraper.jobs TO service_role;


--
-- TOC entry 3804 (class 0 OID 0)
-- Dependencies: 307
-- Name: TABLE role_configs; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON TABLE jobscraper.role_configs TO anon;
GRANT ALL ON TABLE jobscraper.role_configs TO authenticated;
GRANT ALL ON TABLE jobscraper.role_configs TO service_role;


--
-- TOC entry 3805 (class 0 OID 0)
-- Dependencies: 308
-- Name: SEQUENCE role_config_id_seq; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON SEQUENCE jobscraper.role_config_id_seq TO anon;
GRANT ALL ON SEQUENCE jobscraper.role_config_id_seq TO authenticated;
GRANT ALL ON SEQUENCE jobscraper.role_config_id_seq TO service_role;


--
-- TOC entry 3806 (class 0 OID 0)
-- Dependencies: 305
-- Name: TABLE roles; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON TABLE jobscraper.roles TO anon;
GRANT ALL ON TABLE jobscraper.roles TO authenticated;
GRANT ALL ON TABLE jobscraper.roles TO service_role;


--
-- TOC entry 3807 (class 0 OID 0)
-- Dependencies: 306
-- Name: SEQUENCE role_id_seq; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON SEQUENCE jobscraper.role_id_seq TO anon;
GRANT ALL ON SEQUENCE jobscraper.role_id_seq TO authenticated;
GRANT ALL ON SEQUENCE jobscraper.role_id_seq TO service_role;


-- Completed on 2024-05-17 10:25:36

--
-- PostgreSQL database dump complete
--

