--
-- PostgreSQL database dump
--

-- Dumped from database version 15.1 (Ubuntu 15.1-1.pgdg20.04+1)
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-18 08:58:12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 310 (class 1259 OID 30636)
-- Name: jobs; Type: TABLE; Schema: jobscraper; Owner: postgres
--

CREATE TABLE jobscraper.jobs (
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    title text,
    company text,
    short_summary text,
    hard_requirements text,
    job_site text,
    url text,
    location text,
    date_posted date,
    comp_interval text,
    comp_min integer,
    comp_max integer,
    comp_currency text,
    emails text,
    description text,
    searched_title text,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    date_pulled date
);


ALTER TABLE jobscraper.jobs OWNER TO postgres;

--
-- TOC entry 315 (class 1259 OID 34021)
-- Name: users_jobs; Type: TABLE; Schema: jobscraper; Owner: postgres
--

CREATE TABLE jobscraper.users_jobs (
    user_id uuid NOT NULL,
    job_id uuid NOT NULL,
    score text,
    interested boolean,
    desire_score text,
    experience_score text,
    meets_requirements_score text,
    meets_experience_score text,
    email_sent boolean DEFAULT false NOT NULL,
    guidance text
);


ALTER TABLE jobscraper.users_jobs OWNER TO postgres;


--
-- TOC entry 311 (class 1259 OID 30809)
-- Name: user_configs; Type: TABLE; Schema: jobscraper; Owner: postgres
--

CREATE TABLE jobscraper.user_configs (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    key text,
    string_value text,
    int_value integer,
    bool_value boolean,
    user_id uuid
);


ALTER TABLE jobscraper.user_configs OWNER TO postgres;

--
-- TOC entry 312 (class 1259 OID 30812)
-- Name: role_config_id_seq; Type: SEQUENCE; Schema: jobscraper; Owner: postgres
--

ALTER TABLE jobscraper.user_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME jobscraper.role_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 313 (class 1259 OID 32008)
-- Name: users; Type: TABLE; Schema: jobscraper; Owner: postgres
--

CREATE TABLE jobscraper.users (
    id uuid NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    email text,
    location text,
    remote_preference text,
    distance integer,
    results_wanted integer,
    min_salary integer,
    resume text,
    name text,
    is_public boolean DEFAULT false NOT NULL,
    send_emails text DEFAULT 'never'::text NOT NULL,
    onboarding_complete boolean DEFAULT false
);


ALTER TABLE jobscraper.users OWNER TO postgres;

--
-- TOC entry 3667 (class 2606 OID 31352)
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- TOC entry 3669 (class 2606 OID 30820)
-- Name: user_configs role_config_pkey; Type: CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.user_configs
    ADD CONSTRAINT role_config_pkey PRIMARY KEY (id);


--
-- TOC entry 3673 (class 2606 OID 34025)
-- Name: users_jobs users_jko_pkey; Type: CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.users_jobs
    ADD CONSTRAINT users_jko_pkey PRIMARY KEY (user_id, job_id);


--
-- TOC entry 3671 (class 2606 OID 32013)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3674 (class 2606 OID 40000)
-- Name: user_configs user_configs_user_id_fkey; Type: FK CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.user_configs
    ADD CONSTRAINT user_configs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3675 (class 2606 OID 34474)
-- Name: users users_id_fkey; Type: FK CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.users
    ADD CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3676 (class 2606 OID 35954)
-- Name: users_jobs users_jobs_job_id_fkey; Type: FK CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.users_jobs
    ADD CONSTRAINT users_jobs_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobscraper.jobs(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3677 (class 2606 OID 35959)
-- Name: users_jobs users_jobs_user_id_fkey; Type: FK CONSTRAINT; Schema: jobscraper; Owner: postgres
--

ALTER TABLE ONLY jobscraper.users_jobs
    ADD CONSTRAINT users_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES jobscraper.users(id) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- TOC entry 3834 (class 0 OID 0)
-- Dependencies: 310
-- Name: TABLE jobs; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON TABLE jobscraper.jobs TO anon;
GRANT ALL ON TABLE jobscraper.jobs TO authenticated;
GRANT ALL ON TABLE jobscraper.jobs TO service_role;


--
-- TOC entry 3835 (class 0 OID 0)
-- Dependencies: 315
-- Name: TABLE users_jobs; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON TABLE jobscraper.users_jobs TO anon;
GRANT ALL ON TABLE jobscraper.users_jobs TO authenticated;
GRANT ALL ON TABLE jobscraper.users_jobs TO service_role;


--
-- TOC entry 3837 (class 0 OID 0)
-- Dependencies: 311
-- Name: TABLE user_configs; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON TABLE jobscraper.user_configs TO anon;
GRANT ALL ON TABLE jobscraper.user_configs TO authenticated;
GRANT ALL ON TABLE jobscraper.user_configs TO service_role;


--
-- TOC entry 3838 (class 0 OID 0)
-- Dependencies: 312
-- Name: SEQUENCE role_config_id_seq; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON SEQUENCE jobscraper.role_config_id_seq TO anon;
GRANT ALL ON SEQUENCE jobscraper.role_config_id_seq TO authenticated;
GRANT ALL ON SEQUENCE jobscraper.role_config_id_seq TO service_role;


--
-- TOC entry 3839 (class 0 OID 0)
-- Dependencies: 313
-- Name: TABLE users; Type: ACL; Schema: jobscraper; Owner: postgres
--

GRANT ALL ON TABLE jobscraper.users TO anon;
GRANT ALL ON TABLE jobscraper.users TO authenticated;
GRANT ALL ON TABLE jobscraper.users TO service_role;


-- Completed on 2024-06-18 08:58:16

--
-- PostgreSQL database dump complete
--

